function Get-CitrixMachines {
    
    <#
    .SYNOPSIS
    
    .DESCRIPTION
    
    .LINK
    https://github.com/karjona/citrix-odata
    
    .PARAMETER DeliveryController
    Specifies a single Citrix Virtual Apps & Desktops Delivery Controller to collect data from.
    
    .PARAMETER Credential
    Specifies a user account that has permission to send the request. The default is the current user. A minimum of
    read-only administrator permissions on Citrix Virtual Apps & Desktops are required to collect this data.
    
    Enter a PSCredential object, such as one generated by the Get-Credential cmdlet.
    
    .COMPONENT
    citrix-odata
    #>
    
    [CmdletBinding()]
    [OutputType('PSCustomObject')]
    
    param(
    [Parameter(Mandatory=$true)]
    [String]
    $DeliveryController,
    
    [Parameter()]
    [PSCredential]
    $Credential
    )
    
    process {
        try {
            $Query = (
            "`$select=HostedMachineId,DnsName,DesktopGroupId&`$filter=(LifecycleState eq 0) and " +
            "(DesktopGroupId ne null) and (HostedMachineId ne null)"
            )
            
            Write-Progress -Id 1 -Activity "Retrieving managed machines for $DeliveryController"
            if ($Credential) {
                $Machines = Invoke-CitrixMonitorServiceQuery -DeliveryController $DeliveryController `
                -Credential $Credential -Endpoint 'Machines' -Query $Query -ErrorAction Stop
            } else {
                $Machines = Invoke-CitrixMonitorServiceQuery -DeliveryController $DeliveryController `
                -Credential $Credential -Endpoint 'Machines' -Query $Query -ErrorAction Stop
            }
        } catch {
            $ConnectionError = $_
            throw $ConnectionError
        } finally {
            Write-Progress -Id 1 -Activity "Retrieving managed machines for $DeliveryController" -Completed
        }
        $Machines
    }
}
