function Test-CitrixDDCConnectivity {

    <#
    .SYNOPSIS
    Checks for connectivity to the Monitor Service OData API on the specified Citrix Virtual Apps & Desktops
    Delivery Controllers.

    .DESCRIPTION
    The Test-CitrixDDCConnectivity is used as a private function on the citrix-odata module to test for a valid
    connection to the Monitor Service OData API on the specified Citrix Virtual Apps & Desktops Delivery
    Controllers.

    This cmdlet takes a required parameter: a list of Citrix Virtual Apps & Desktops Delivery Controllers.
    Without any other parameters, it will use the current user to connect to the DDCs and test if the API is
    available.
    
    It will return an array with the DDCs that responded with a valid Monitor Service OData API connection. If the
    cmdlet cannot make a valid connection to any of the specified Delivery Controllers it will end the execution of
    the PowerShell pipeline with an error.

    .LINK
    https://github.com/karjona/citrix-odata

    .PARAMETER DeliveryControllers
    Specifies a single Citrix Virtual Apps & Desktops Delivery Controller or an array of Citrix DDCs from
    different Sites to collect data from.

    .PARAMETER Credential
    Specifies a user account that has permission to send the request. The default is the current user. A minimum of
    read-only administrator permissions on Citrix Virtual Apps & Desktops are required to collect this data.

    Enter a PSCredential object, such as one generated by the Get-Credential cmdlet.

    .COMPONENT
    citrix-odata
    #>

    [CmdletBinding()]
    [OutputType([String[]])]

    param(
        [Parameter(Mandatory=$true)]
        [String[]]
        $DeliveryControllers,

        [Parameter()]
        [PSCredential]
        $Credential
    )

    process {
        foreach ($ddc in $DeliveryControllers) {
            try {
                if ($Credential) {
                    Invoke-RestMethod -Uri "http://$ddc/Citrix/Monitor/OData/v3/Data/" `
                    -Credential $Credential | Out-Null
                } else {
                    Invoke-RestMethod -Uri "http://$ddc/Citrix/Monitor/OData/v3/Data/" `
                    -UseDefaultCredentials | Out-Null
                }
            } catch {
                $ConnectionError = $_
                # Handle 401 (invalid credentials) error
                if ($ConnectionError.Exception.Response.StatusCode) {
                    if ($ConnectionError.Exception.Response.StatusCode.ToString() -eq 'Unauthorized') {
                        if (!$Credential) {
                            Write-Error ("The current user does not have at least read-only administrator " +
                            "permissions on $ddc.")
                        } else {
                            Write-Error ("The supplied credentials do not have at least read-only administrator " +
                            "permissions on $ddc.")
                        }
                    # There's a web server on that address, but responded with an error (404, 500...)
                    } else {
                        Write-Error ("The server on $ddc responded with an error: " +
                        "$($ConnectionError.Exception.Message)")
                    }
                } else {
                    # Handle DNS resolution errors
                    if ($ConnectionError.Exception.Status.ToString() -eq 'NameResolutionFailure') {
                        Write-Error "Could not find host $ddc."
                    # Handle all other errors
                    } else {
                        Write-Error ("An error occurred while trying to connect to $ddc. Check network " +
                        "connectivity and that the specified host is a Citrix Delivery Controller.`r`n" +
                        "$($ConnectionError.Exception.Message)")
                    }
                }
                # Remove the failed DDC from the DDCs list
                $DeliveryControllers = $DeliveryControllers | Where-Object -FilterScript {$_ -ne $ddc}
            } finally {
                if (!$DeliveryControllers) {
                    throw "Could not connect to any of the specified Delivery Controllers."
                }
            }
        }
        $DeliveryControllers
    }
}
